# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('person_create_date', models.DateTimeField()),
                ('person_age', models.IntegerField()),
                ('person_other', models.CharField(max_length=200)),
            ],
        ),
    ]
