# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
