# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, null=True)),
                ('data', models.CharField(max_length=1000, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('create_time', models.DateTimeField()),
                ('response', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='data',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
