# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_auto_20160620_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
