# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0005_log_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50, null=True)),
                ('f_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test1.Request')),
            ],
        ),
    ]
