# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0006_request_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_data',
            name='value',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
