# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0008_auto_20160621_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='response_len',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='response_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
